sudo: false
language: python
matrix:
  include:
    - os: linux
      python: 3.4
      env: TOX_ENV=py34
    - os: linux
      python: 3.5
      env: TOX_ENV=py35
    - os: linux
      python: 3.6
      env: TOX_ENV=py36
    - os: linux
      python: pypy3
      env: TOX_ENV=pypy3
    - os: osx
      language: generic
      env: TOX_ENV=py36
      before_install:
        - brew update
        - brew upgrade python
        - python3 -m venv venv
        - source venv/bin/activate
    - os: linux
      python: 3.6
      env: TOX_ENV=lint
    - os: linux
      python: 3.6
      env: TOX_ENV=cover
install:
  - pip install pipenv
  - pipenv sync
script: pipenv run tox -e $TOX_ENV
